//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "new"
 * identifier -> Identifier()
 * nodeToken1 -> "("
 * nodeToken2 -> ")"
 */
public class AllocationExpression implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;

   public AllocationExpression(NodeToken n0, Identifier n1, NodeToken n2, NodeToken n3) {
      nodeToken = n0;
      identifier = n1;
      nodeToken1 = n2;
      nodeToken2 = n3;
   }

   public AllocationExpression(Identifier n0) {
      nodeToken = new NodeToken("new");
      identifier = n0;
      nodeToken1 = new NodeToken("(");
      nodeToken2 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

