//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "."
 * nodeToken1 -> "length"
 */
public class ArrayLength implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;

   public ArrayLength(PrimaryExpression n0, NodeToken n1, NodeToken n2) {
      primaryExpression = n0;
      nodeToken = n1;
      nodeToken1 = n2;
   }

   public ArrayLength(PrimaryExpression n0) {
      primaryExpression = n0;
      nodeToken = new NodeToken(".");
      nodeToken1 = new NodeToken("length");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

