//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "["
 * primaryExpression1 -> PrimaryExpression()
 * nodeToken1 -> "]"
 */
public class ArrayLookup implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public PrimaryExpression primaryExpression1;
   public NodeToken nodeToken1;

   public ArrayLookup(PrimaryExpression n0, NodeToken n1, PrimaryExpression n2, NodeToken n3) {
      primaryExpression = n0;
      nodeToken = n1;
      primaryExpression1 = n2;
      nodeToken1 = n3;
   }

   public ArrayLookup(PrimaryExpression n0, PrimaryExpression n1) {
      primaryExpression = n0;
      nodeToken = new NodeToken("[");
      primaryExpression1 = n1;
      nodeToken1 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

