//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "int"
 * nodeToken1 -> "["
 * nodeToken2 -> "]"
 */
public class ArrayType implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;

   public ArrayType(NodeToken n0, NodeToken n1, NodeToken n2) {
      nodeToken = n0;
      nodeToken1 = n1;
      nodeToken2 = n2;
   }

   public ArrayType() {
      nodeToken = new NodeToken("int");
      nodeToken1 = new NodeToken("[");
      nodeToken2 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

