//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "class"
 * identifier -> Identifier()
 * nodeToken1 -> "extends"
 * identifier1 -> Identifier()
 * nodeToken2 -> "{"
 * nodeListOptional -> ( VarDeclaration() )*
 * nodeListOptional1 -> ( MethodDeclaration() )*
 * nodeToken3 -> "}"
 */
public class ClassExtendsDeclaration implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeToken nodeToken1;
   public Identifier identifier1;
   public NodeToken nodeToken2;
   public NodeListOptional nodeListOptional;
   public NodeListOptional nodeListOptional1;
   public NodeToken nodeToken3;

   public ClassExtendsDeclaration(NodeToken n0, Identifier n1, NodeToken n2, Identifier n3, NodeToken n4, NodeListOptional n5, NodeListOptional n6, NodeToken n7) {
      nodeToken = n0;
      identifier = n1;
      nodeToken1 = n2;
      identifier1 = n3;
      nodeToken2 = n4;
      nodeListOptional = n5;
      nodeListOptional1 = n6;
      nodeToken3 = n7;
   }

   public ClassExtendsDeclaration(Identifier n0, Identifier n1, NodeListOptional n2, NodeListOptional n3) {
      nodeToken = new NodeToken("class");
      identifier = n0;
      nodeToken1 = new NodeToken("extends");
      identifier1 = n1;
      nodeToken2 = new NodeToken("{");
      nodeListOptional = n2;
      nodeListOptional1 = n3;
      nodeToken3 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

