//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "<"
 * primaryExpression1 -> PrimaryExpression()
 */
public class CompareExpression implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public PrimaryExpression primaryExpression1;

   public CompareExpression(PrimaryExpression n0, NodeToken n1, PrimaryExpression n2) {
      primaryExpression = n0;
      nodeToken = n1;
      primaryExpression1 = n2;
   }

   public CompareExpression(PrimaryExpression n0, PrimaryExpression n1) {
      primaryExpression = n0;
      nodeToken = new NodeToken("<");
      primaryExpression1 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

