//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> ","
 * formalParameter -> FormalParameter()
 */
public class FormalParameterRest implements Node {
   public NodeToken nodeToken;
   public FormalParameter formalParameter;

   public FormalParameterRest(NodeToken n0, FormalParameter n1) {
      nodeToken = n0;
      formalParameter = n1;
   }

   public FormalParameterRest(FormalParameter n0) {
      nodeToken = new NodeToken(",");
      formalParameter = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

