//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * type -> Type()
 * identifier -> Identifier()
 */
public class FormalParameter implements Node {
   public Type type;
   public Identifier identifier;

   public FormalParameter(Type n0, Identifier n1) {
      type = n0;
      identifier = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

