//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * mainClass -> MainClass()
 * nodeListOptional -> ( TypeDeclaration() )*
 * nodeToken -> <EOF>
 */
public class Goal implements Node {
   public MainClass mainClass;
   public NodeListOptional nodeListOptional;
   public NodeToken nodeToken;

   public Goal(MainClass n0, NodeListOptional n1, NodeToken n2) {
      mainClass = n0;
      nodeListOptional = n1;
      nodeToken = n2;
   }

   public Goal(MainClass n0, NodeListOptional n1) {
      mainClass = n0;
      nodeListOptional = n1;
      nodeToken = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

