//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "."
 * identifier -> Identifier()
 * nodeToken1 -> "("
 * nodeOptional -> ( ExpressionList() )?
 * nodeToken2 -> ")"
 */
public class MessageSend implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeToken nodeToken1;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken2;

   public MessageSend(PrimaryExpression n0, NodeToken n1, Identifier n2, NodeToken n3, NodeOptional n4, NodeToken n5) {
      primaryExpression = n0;
      nodeToken = n1;
      identifier = n2;
      nodeToken1 = n3;
      nodeOptional = n4;
      nodeToken2 = n5;
   }

   public MessageSend(PrimaryExpression n0, Identifier n1, NodeOptional n2) {
      primaryExpression = n0;
      nodeToken = new NodeToken(".");
      identifier = n1;
      nodeToken1 = new NodeToken("(");
      nodeOptional = n2;
      nodeToken2 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

