//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "!"
 * expression -> Expression()
 */
public class NotExpression implements Node {
   public NodeToken nodeToken;
   public Expression expression;

   public NotExpression(NodeToken n0, Expression n1) {
      nodeToken = n0;
      expression = n1;
   }

   public NotExpression(Expression n0) {
      nodeToken = new NodeToken("!");
      expression = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

