//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * type -> Type()
 * identifier -> Identifier()
 * nodeToken -> ";"
 */
public class VarDeclaration implements Node {
   public Type type;
   public Identifier identifier;
   public NodeToken nodeToken;

   public VarDeclaration(Type n0, Identifier n1, NodeToken n2) {
      type = n0;
      identifier = n1;
      nodeToken = n2;
   }

   public VarDeclaration(Type n0, Identifier n1) {
      type = n0;
      identifier = n1;
      nodeToken = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

